services:
  - type: web
    name: portfolio
    runtime: php
    region: singapore
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm ci && npm run build
    startCommand: ./start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: portfolio
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_DATABASE
        value: portfolio
      - key: DB_HOST
        fromService:
          type: pgsql
          name: portfolio-db
          property: host
      - key: DB_PORT
        fromService:
          type: pgsql
          name: portfolio-db
          property: port
      - key: DB_USERNAME
        fromService:
          type: pgsql
          name: portfolio-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pgsql
          name: portfolio-db
          property: password
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: MAIL_MAILER
        value: log
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local

databases:
  - name: portfolio-db
    databaseName: portfolio
    region: singapore
    plan: free
